language: go
go:
  - "1.12"
os:
  - "linux"
  - "osx"
  - "windows"
env:
  - GO111MODULE=on
before_script:
  - git checkout -- .
script:
  - go clean ./...
  - gofmt -l .
  - go vet ./...
  - go test -v ./...
  - go build -o ./bin/rg-server
notifications:
  slack: it-slaves:xRVaXMWqCiZPZLOFTiXe8YoY
