language: go
go:
  - "1.12"
os:
  - "linux"
  - "osx"
  # - "windows" # FIXME: 윈도우 빌드 속도가 개선될 때 다시 추가
env:
  - GO111MODULE=on
before_install:
  - go get -v golang.org/x/lint/golint
script:
  - go clean ./...
  - gofmt -l .
  - golint ./...
  - go vet ./...
  - go test -v ./...
  - go build -o ./bin/rg-server
notifications:
  slack: it-slaves:xRVaXMWqCiZPZLOFTiXe8YoY
