web:
  addr: localhost:8000
session:
  type: redis
  name: rg_session
  maxAge: 86400 # for a day
  domain: localhost
oauth:
  kakao:
    authorizeURL: https://kauth.kakao.com/oauth/authorize
    tokenURL: https://kauth.kakao.com/oauth/token
    redirectURL: http://localhost:8080/oauth/callback/kakao
    userProfileURL: https://kapi.kakao.com/v2/user/me
  naver:
    authorizeURL: https://nid.naver.com/oauth2.0/authorize
    tokenURL: https://nid.naver.com/oauth2.0/token
    redirectURL: http://localhost:8080/oauth/callback/naver
    userProfileURL: https://openapi.naver.com/v1/nid/me
  google:
    redirectURL: http://localhost:8080/oauth/callback/google
    scopes:
      - https://www.googleapis.com/auth/userinfo.email
      - https://www.googleapis.com/auth/userinfo.profile
    userProfileURL: https://www.googleapis.com/oauth2/v3/userinfo
redis:
  addrs: [":6379"]
  minIdleConns: 2
mysql:
  user: "root"
  addr: "localhost:3306"
  db: "rental_games"
  params:
    charset: "utf8mb4"
  collation: "utf8mb4_general_ci"
  location: "Asia/Seoul"
  dialTimeout: "50ms"
  readTimeout: "200ms"
  writeTimeout: "400ms"
